config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show,:destroy]
  resources :items, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'rentalarea'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_rentals' => 'reservations#your_rentals'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |value| %>
            toastr.error('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |key, value| %>
            <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
            toastr['<%= type %>']('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_navbar.html.erb
  <!-- Static navbar -->
  <% if (!user_signed_in?) %>
      <nav class="navbar navbar-default">
  <% else %>
      <nav class="navbar navbar-login">
  <% end %>
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "EveryShare", root_path, class: "navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li>
              <% if (user_signed_in?) %>
                <button class="btn btn-form btn-small">
                  <%= link_to "新規アイテム登録", new_item_path, style: "color: white; text-decoration: none;" %>
                </button>
              <% end %>
              </li>
              
              <% if (!user_signed_in?) %>
                <li><%= link_to "ログイン" , new_user_session_path %></li>
                <li><%= link_to "サインアップ" , new_user_registration_path %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                      role="button" aria-haspopup="true" aria-expanded="false">
                      <% if current_user.image? %>
                        <img src='<%= current_user.image %>'  class = "icon_image">
                      <% else %>
                        <img src="<%= asset_path "default.png" %>"  class = "icon_image">
                      <% end %>
                      <%= current_user.name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "出品一覧", items_path %></li>
                    <li><%= link_to "アイテム新規登録", new_item_path %></li>
                    <li><%= link_to "あなたのアイテムへの予約", your_reservations_path %></li>
                    <li><%= link_to "あなたの予約", your_rentals_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                    <li><%= link_to "プロフィール編集" , edit_user_registration_path %></li>
                    <li><%= link_to "ログアウト" , destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>