config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show,:destroy]
  resources :items, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'rentalarea'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_rentals' => 'reservations#your_rentals'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :item

  has_many :reviews, dependent: :destroy

  scope :guest_reviews_search , -> (reservation_id,item_id){where(
    id: reservation_id,
    item_id: item_id
  ).first}

  scope :host_reviews_search , -> (reservation_id,item_id,guest_id){where(
   id: reservation_id,
   item_id: item_id,
   user_id: guest_id
  ).first}
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      item = Item.find(params[:item_id])
  
      if current_user == item.user
        flash[:alert] = "自分のアイテムには予約出来ません!"
      else
        start_date = Date.parse(reservation_params[:start_date])
        end_date = Date.parse(reservation_params[:end_date])
        days = (end_date - start_date).to_i + 1
  
        @reservation = current_user.reservations.build(reservation_params)
        @reservation.item = item
        @reservation.price = item.price
        @reservation.total = item.price * days
        @reservation.save
  
        flash[:notice] = "予約完了!"
      end
      redirect_to item
    end
  
    def your_rentals
      @rentals = current_user.reservations.where("reservations.start_date > ?", DateTime.now).order(start_date: :asc)
    end
  
    def your_reservations
      @items = current_user.items
    end
  
    private
      def reservation_params
        params.require(:reservation).permit(:start_date, :end_date)
      end
  end

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span> ¥<%= @items.price %></span>
    <span class="pull-right">1日</span>
  </div>
  <div class="panel-body">    
    <%= form_for([@items, @items.reservations.new]) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <label>開始日</label>
          <%= f.text_field :start_date, readonly: true, placeholder: "Start", class: "form-control datepicker" %>
        </div>
        <div class="col-md-6">
        <label>返却日</label>
          <%= f.text_field :end_date, readonly: true, placeholder: "Return", class: "form-control datepicker", disabled: true %>
        </div>
      </div>

      <h4 class="message-alert text-center"><span id="message"></span></h4>
      <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>値段</td>
              <td class="text-right">¥<%= @items.price %></td>
            </tr>
            <tr>
              <td>日数</td>
              <td class="text-right">x <span id="reservation_nights"></span></td>
            </tr>
            <tr>
              <td class="total">合計</td>
              <td class="text-right">¥<span id="reservation_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <br/>
      <%= f.submit "予約する", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>
    <% end %>
  </div>
</div>


<script>

  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

    unavailableDates = [];

    $.ajax({
      url: '<%= preload_item_path(@items) %>',
      dateTyp: 'json',
      success: function(data) {

        $.each(data, function(arrID, arrValue) {
            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
              unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
            }
        });

        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_end_date').datepicker("option", "minDate", selected);
            $('#reservation_end_date').attr("disabled", false);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_item_path(@items) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @items.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });

          }
        });

        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_item_path(@items) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @items.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });
          }
        });
      }
    });



  });
</script>

app/views/reservations/your_rentals.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "あなたの出品アイテム一覧", items_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "あなたのアイテムへの予約一覧", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "あなたの予約一覧", your_rentals_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        あなたの予約一覧
      </div>
      <div class="panel-body">

        <% @rentals.each do |rental| %>
          <div class="row">
            <div class="col-md-2">
                <div class="text-babu"><%= "開始日" %></div><%= rental.start_date.strftime('%v') %><br/>
                <div class="text-babu"><%= "返却日" %></div><%= rental.end_date.strftime('%v') %>
            </div>
            <div class="col-md-3">
            <%= link_to item_path(rental.item) do %>
              <%= image_tag rental.item.cover_photo(:thumbmid)%>
            <% end %>
            </div>
            <div class="col-md-4">
            <%= link_to item_path(rental.item) do %>
              <%= link_to rental.item.item_name, item_path(rental.item) %><br/><br/>
            <% end %>
              <span>
                <% if rental.item.user.image? %>
                  <img src='<%= rental.item.user.image %>'  class = "icon_image_large">
                <% else %>
                  <img src="<%= asset_path "default.png" %>"  class = "icon_image_large">
                <% end %>
                <%= link_to user_path(rental.item.user) do %>
                    <%= rental.item.user.name %>
                <% end %>
              </span>
            </div>
            <div class="col-md-3 text-right">
            <%= render partial: "reviews/guest_form", locals: {reservation: rental} %>
            </div>  
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/your_reservations.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "あなたの出品アイテム一覧", items_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "あなたのアイテムへの予約一覧", your_reservations_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "あなたの予約一覧", your_rentals_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        あなたのアイテムへの予約
      </div>
      <div class="panel-body">

        <% @items.each do |item| %>
            <% item.reservations.each do |reservation| %>
                <div class="row">
                  <div class="col-md-2">
                    <div class="text-babu"><%= "開始日" %></div><%= reservation.start_date.strftime('%v') %><br/>
                    <div class="text-babu"><%= "返却日" %></div><%= reservation.end_date.strftime('%v') %>
                  </div>
                  <div class="col-md-3">
                    <%= link_to item_path(reservation.item) do %>
                        <%= image_tag reservation.item.cover_photo(:thumbmid) %>
                    <% end %>
                  </div>
                  <div class="col-md-4">
                    <%= link_to reservation.item.item_name, item_path(reservation.item) %><br/><br/>
                    <span>
                      <%= "Guest" %><br/>
                      <%= link_to user_path(reservation.user) do %>
                        <% if reservation.user.image? %>
                          <img src='<%= reservation.user.image %>'  class = "icon_image_large">
                        <% else %>
                          <img src="<%= asset_path "default.png" %>"  class = "icon_image_large">
                        <% end %>
                        <%= reservation.user.name %>
                      <% end %>
                    </span>
                  </div>
                  <div class="col-md-3 text-right">
                    <%= render partial: "reviews/host_form", locals: {reservation: reservation} %>
                  </div>
                </div>
                <hr/>

            <% end %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>