config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show,:destroy]
  resources :items, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'rentalarea'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_rentals' => 'reservations#your_rentals'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/item.rb
class Item < ApplicationRecord
    
    belongs_to :user
    has_many :photos, dependent: :destroy
    has_many :reservations, dependent: :destroy

    has_many :guest_reviews, dependent: :destroy
    has_many :host_reviews, dependent: :destroy
    has_many :reviews, dependent: :destroy

    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    validates :main_category, presence: true
    validates :sub_category, presence: true
    validates :status, presence: true
    validates :price, numericality: true, if: :price_check

    def cover_photo(size)
      if self.photos.length > 0
        self.photos[0].image.url(size)
      else
        "blank.jpg"
      end
    end

    def average_rating
      guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
    end

    def price_check
      self.price.present?
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :location, :update]

  def index
    @items = current_user.items
  end

  def new
    @item = current_user.items.new
  end

  def create
    @item = current_user.items.new(item_params)
    
    if @item.save
      redirect_to pricing_item_path(@item), notice: "詳細登録して下さい"
    else
      flash[:alert] = "入力不足があります"
      render :new
    end
  end

  def show
    @photos = @items.photos
    @guest_reviews = @items.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @items.photos
  end

  def location
  end

  def update
    new_params = item_params
    new_params.merge(active: true) if is_ready_item

    if @items.update(new_params)
      if is_ready_item
        redirect_to item_path(@items), notice:"詳細登録しました！"
      else
        flash[:notice] = "保存しました"
        redirect_back(fallback_location: request.referer)
      end
    else
      flash[:alert] = "入力不足があります"
      redirect_back(fallback_location: request.referer)
    end
     
  end

  def destroy
    @items.destroy
    redirect_to items_path, notice:"削除しました！"
  end

  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @items.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @items)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, items)
      check = items.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_item
      @items = Item.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @items.user_id
    end

    def is_ready_item
      @items.active && @items.price.present? && @items.item_name.present? && @items.photos.present? && @items.address.present?
    end

    def item_params
      params.require(:item).permit(:main_category, :sub_category, :status, :item_name, :summary, :price, :address, :active)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "アイテム概要", listing_item_path, class: "sidebar-link" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "値段", pricing_item_path, class: "sidebar-link" %>
    <% if !@items.price.blank? %>
      <span class="pull-right text-babu"><i id: price_check, class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "詳細", description_item_path, class: "sidebar-link" %>
    <% if !@items.item_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>  
  </li>
  <li class="sidebar-item">
    <%= link_to "写真", photo_upload_item_path, class: "sidebar-link" %>
    <% if !@items.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "レンタルエリア", rentalarea_item_path, class: "sidebar-link" %>
    <% if !@items.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@items.active && !@items.price.blank? && !@items.item_name.blank? && !@items.photos.blank? && !@items.address.blank? %>

<%= form_for @items do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "最終登録", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>
<%= "全てをチェックして最終登録ボタンを押して下さい" %>

app/views/items/_items_list.html.erb
<% @items.each do |item| %>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag item.cover_photo(:thumb) , class: "item_list_image"%>
        </div>
        <div class="panel-body">
          <%= link_to item.item_name, item %><br/>
          <%= item.address %><br/>
          ¥<%= item.price %><br/>
          <%= item.main_category %> - <%= item.sub_category %><br/>
          <%= item.status %>
          <div id="star_<%= item.id %>"></div>
          <%= pluralize(item.average_rating, "review") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= item.id %>').raty({
        starOff: '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        readOnly: true,
        score: <%= item.average_rating %>
      });
    </script>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'item_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        詳細
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @items do |f| %>

            <div class="row">
              <div class="form-group">
                <label>アイテム名</label>
                <%= f.text_field :item_name, placeholder: "アイテム名", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>詳細</label>
                <%= f.text_area :summary, rows: 5, placeholder: "アイテム説明", id: "summary", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "アイテム説明保存", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "あなたの出品アイテム一覧", items_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "あなたの予約一覧", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "あなたのアイテムへの予約一覧", your_rentals_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        出品一覧
      </div>
      <div class="panel-body">

        <% @items.each do |item| %>
          <div class="row">
            <div class="col-md-3">
              <%= image_tag item.cover_photo(:thumbmid)%>
            </div>
            <div class="col-md-5">
              <h4><%= link_to item.item_name, item_path(item.id)%></h4>
            </div>
            <div class="col-md-2 right">
              <%= link_to "編集", listing_item_path(item), class: "btn btn-form" %>
            </div>
            <div class="col-md-2 right">
              <%= link_to "削除", item_path(item.id), method: :delete, data: {confirm: '本当にいいですか?'}, class: "btn btn-danger" %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'item_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        アイテム登録
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @items do |f| %>

            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>メインカテゴリー</label>
                  <%= f.select :main_category, [["アウトドア", "アウトドア"], ["スポーツ", "スポーツ"], ["旅行アイテム", "旅行アイテム"], ["ハウスアイテム", "ハウスアイテム"], ["その他", "その他"]],
                                id: "main_category", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>サブカテゴリー</label>
                  <%= f.select :sub_category, [["洋服", "洋服"], ["グッズ", "グッズ"], ["小物", "小物"], ["その他", "その他"]],
                                id: "sub_category", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>アイテムの状態</label>
                  <%= f.select :status, [["綺麗", "綺麗"], ["普通", "普通"], ["汚い", "汚い"], ["ボロボロ", "ボロボロ"]],
                                id: "status", prompt: "Select...", class: "form-control" %>
                </div>
              </div>
            <div class="col-md-4 select">
              <div><%= f.submit "概要保存", class: "btn btn-normal" %></div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/items/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'item_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Location
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @items do |f| %>

            
            <div class="row">
              <div class="form-group">
                <label>Address</label>
                <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    アイテム登録
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @item do |f| %>

        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>メインカテゴリー</label>
              <%= f.select :main_category, [["アウトドア", "アウトドア"], ["スポーツ", "スポーツ"], ["旅行アイテム", "旅行アイテム"], ["ハウスアイテム", "ハウスアイテム"], ["その他", "その他"]],
                            id: "main_category", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>サブカテゴリー</label>
              <%= f.select :sub_category, [["洋服", "洋服"], ["グッズ", "グッズ"], ["小物", "小物"], ["その他", "その他"]],
                            id: "sub_category", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>アイテム状態</label>
              <%= f.select :status, [["綺麗", "綺麗"], ["普通", "普通"], ["汚い", "汚い"], ["ボロボロ", "ボロボロ"]],
                            id: "status", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
        <div class="col-md-4 select">
          <div><%= f.submit "仮登録", class: "btn btn-normal" %></div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/items/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'item_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        写真
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @items, url: item_photos_path(@items), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> 写真選択
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "写真保存", class: "btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/items/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'item_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        値段
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @items do |f| %>

            <div class="row">
              <div class="form-group">
                <label>値段</label>
                <%= f.number_field :price, placeholder: "￥100",id: "price", class: "form-control", required: true, min: 0, max: 10000000 %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "値段設定保存", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/items/rentalarea.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'item_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        レンタルエリア
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @items do |f| %>

            
            <div class="row">
              <div class="form-group">
                <label>レンタルエリア</label>
                <%= f.text_field :address, placeholder: "レンタル可能エリアはどこですか?", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "レンタルエリア保存", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/items/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-8">
    <%= image_tag @items.cover_photo(nil), width: "100%", class: "item_show_image" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @items.item_name %></h1>
        <h3><%= @items.address %></h3>
      </div>
      <div class="col-md-4 text-center">
      <br/><br/>
        <% if @items.user.image? %>
          <img src='<%= @items.user.image %>'  class = "icon_image_large">
        <% else %>
          <img src="<%= asset_path "default.png" %>"  class = "icon_image_large">
        <% end %>
        <br/><br/>
        <%= @items.user.name %>
      </div>
    </div>
    <hr/>

    <!-- items Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-4">
          <%= t('activerecord.attributes.item.Main category') %>
        </div>
        <div class="col-md-4">
          <%= t('activerecord.attributes.item.Sub category') %>
        </div>
        <div class="col-md-4">
          <%= t('activerecord.attributes.item.Sutatus') %>
        </div>
      </div>

      <div class="row text-center">
        <h4><div class="col-md-4"><%= @items.main_category %></div></h4>
        <h4><div class="col-md-4"><%= @items.sub_category %></div></h4>
        <h4><div class="col-md-4"><%= @items.status %></div></h4>
      </div>


    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>アイテム説明</h3>
        <p><%= @items.summary %></p>
      </div>
    </div>
    <hr/>


    <!-- Carousel -->
    <div class="row">
      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>
    </div>
    <hr/>

    <!-- REVIEWS -->
    <div class="row">
      <div class="col-md-12">
        <h3>
          <%= pluralize(@guest_reviews.count, t('activerecord.attributes.item.Review')) %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%= render "reviews/guest_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>

    <!-- GOOGLE MAP -->
    <div class="row">
      <h3>レンタルエリア</h3>
      <div id="map" style="width: 100%; height: 400px"></div>

      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
      <script>
        let map

        function initMap(){
          geocoder = new google.maps.Geocoder()

          map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: <%= @items.latitude %>, lng: <%= @items.longitude %>},
            zoom: 12,
                });

          marker = new google.maps.Marker({
            position: {lat: <%= @items.latitude %>, lng: <%= @items.longitude %>},
            map: map
          });

          var myCircle = new google.maps.Circle({
          strokeColor: '#FF0000',
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: '#FF0000',
          fillOpacity: 0.35,
          map: map,
          center: {lat: <%= @items.latitude %>, lng: <%= @items.longitude %>},
          radius: 5000
        });
        }
      </script>
    </div>
    <hr/>

  </div>
        <!-- RIGHT PANEL -->
    <div class="col-md-4">
      <!-- Reservation Form -->
      <%= render 'reservations/form' %>
    </div>
</div>

<script>
  $('#average_rating').raty({
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    readOnly: true,
    score: <%= @items.average_rating %>
  });
</script>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>