config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show,:destroy]
  resources :items, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'rentalarea'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_rentals' => 'reservations#your_rentals'
  get '/your_reservations' => 'reservations#your_reservations'

  get 'search' => 'pages#search'
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :item
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

    def create
      @item = Item.find(params[:item_id])
  
      if params[:images]
        params[:images].each do |img|
          @item.photos.create(image: img)
        end
  
        @photos = @item.photos
        redirect_back(fallback_location: request.referer, notice: "写真登録しました")
      end
    end
  
    def destroy
      @photo = Photo.find(params[:id])
      @items = @photo.item
  
      @photo.destroy
      @photos = Photo.where(item_id: @items.id)
  
      respond_to :js
    end
  end
  

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to item_photo_path(photo.item_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")
<% if @items.photos.blank? %>
  $('#photo_check').hide();
<% end %>

<% if !@items.active && !@items.price.blank? && !@items.item_name.blank? && !@items.photos.blank? && !@items.address.blank? %>
    $('#publish_button').attr('disabled', false);
<% else %>
    $('#publish_button').attr('disabled', true);
<% end %>